### ISSUE TITLE
error `go-layerfs: could not ReadDir because n >= 0 is not supported`

### ISSUE THREAD

**Issue by oeaniz** [dschmidt/go-layerfs#8]
I tried to use layerfs with 2 `embed.FS`, but when i was walking the filesystem I saw the message
`views: go-layerfs: could not ReadDir because n >= 0 is not supported: .`

When I read the docs for fs.ReadDirFile (https://github.com/golang/go/blob/master/src/io/fs/fs.go#L129), there are cases for `n > 0` and `n <= 0`, so i think the check in DirFile.ReadDir should only fail for `n > 0` (and not for `n == 0`)  https://github.com/dschmidt/go-layerfs/blob/a0bce2dc294f4c856d88f7668bfab1f13a34ce5f/files.go#L23-L27

**Comment by dschmidt** [comment]
Hey,

thanks for trying out go-layerfs and opening this ticket!

The problem here is that when we read only a partial file list, we don't know what we need to overlay or not. We need to read the whole directory, so we can compute the overlay.

Can you post a minimal reproducing example? Then we can look for a solution together.

**Comment by oeaniz** [comment]
For partial file lists, this is indeed a bit more tricky, but when `n == 0` we are requesting the complete directorylisting.

(relevant text snippet from  the [go-docs mentioned earlier](https://github.com/golang/go/blob/master/src/io/fs/fs.go#L129):)
> If n <= 0, ReadDir returns all the DirEntry values from the directory in a single slice.

I'm wrapping it in a `http.FS` as a source for the html template engine of gofiber (https://github.com/gofiber/template) so it's going to take some time to craft up a minimal example.

**Comment by dschmidt** [comment]
Ah, misread the intention of your ticket, I thought you wanted partial directory listing. 

Yes, sounds good. Wanna send a PR to change the check?

**Comment by oeaniz** [comment]
thank you for accepting the PR
